### ISSUE TITLE
Pushing any of the buttons at the top hangs hard

### ISSUE THREAD

**Issue by BartMassey** [rickyhan/crabs#1]
Unfortunately, if I press any of the step, fast forward or stop buttons nothing happens: the UI just hangs hard and I have to reload the page. Animation keeps going but the program doesn't run; hitting \<esc> doesn't help.

I managed to play through the first level with \<ctrl-Return> and that seemed to work.

Debian Linux, Google Chrome Version 73.0.3642.0 (Official Build) dev (64-bit) and Firefox 65.0 (64-bit)

**Comment by 0b01** [comment]
I think it's fixed now. The game framework has some issues with resizing on the web.

**Comment by BartMassey** [comment]
Thanks! Yeah, it works now. Unfortunately the game starts sized way too big to fit on the screen now, but I was able to scale it down and play a couple of rounds. Fun game!
